// B2W + JasonAI unified preview. Content remains reviewable before historical visual merge.
const pages={
"/":{eyebrow:"B2W / Augmented decisions",title:"Make information useful.",lead:"We design and build connected operational systems for teams that work in the real world.",sections:[["Past work","Practical systems spanning engineering, product development, reporting and operational decision-making.",[["Operational intelligence","Dashboards that turn changing data into decisions."],["Enterprise workflows","Clear interfaces that simplify complex work."],["Connected systems","Automation that reduces handoffs and lost information."]]],["How we work","Learn the operation before automating it.",[["01 / Understand","Map people, tools, decisions and gaps."],["02 / Design","Prototype the workflow and establish approval checkpoints."],["03 / Implement","Connect the systems, test and refine."]]]],links:[["Explore our work","/work"],["Meet JasonAI","/jasonai"]]},
"/work":{eyebrow:"B2W / Portfolio",title:"Past work",lead:"Team experience across engineering, operations and applied software.",sections:[["Selected experience","Representative capabilities, not invented client case studies.",[["Operations dashboards","Reliability, risk and performance reporting across complex assets."],["Workflow software","Requirements, user journeys and interfaces for internal teams."],["Engineering research","Hardware, buildings and applied systems thinking."]]]],links:[["How we work","/how-we-work"],["JasonAI","/jasonai"]]},
"/how-we-work":{eyebrow:"B2W / Method",title:"How we work",lead:"Each stage creates a concrete output that the team can inspect.",sections:[["01 / Discover","Understand the people and process.",[["Map","Identify channels, actors, source systems and manual decisions."],["Confirm","Select one costly operational problem and define the improvement."]]],["02 / Design","Make the proposed workflow testable.",[["Prototype","Walk through screens and real cases."],["Control","Agree on permissions, approvals and exceptions."]]],["03 / Implement","Deliver and refine with users.",[["Connect","Integrate the existing tools first."],["Validate","Measure outcomes and tune the system."]]]],links:[["Past work","/work"],["Contact","/contact"]]},
"/perspectives":{eyebrow:"B2W / Perspectives",title:"Perspectives",lead:"Working notes on connected information, decisions and human oversight.",sections:[["Themes","Topics for future articles; not published articles.",[["Connected information","Build on a dependable memory of what happened."],["Reviewable decisions","Turn communications into actions people can approve."],["Applied AI","Design for operating teams instead of demonstrations alone."]]]],links:[["How we work","/how-we-work"]]},
"/jasonai":{eyebrow:"JasonAI / Executive secretary",title:"Work moves. Jason remembers.",lead:"An executive secretary for general contractor owners. Share the conversations you choose; Jason organizes project context, surfaces commitments and suggests actions.",sections:[["What Jason does","Works with your existing communications and tools.",[["Listens with permission","Use selected messages, voice notes and shared files as context."],["Remembers the business","Connect project, labor and delivery updates into one picture."],["Acts with oversight","Review proposed updates and replies before they take effect."]]]],links:[["For general contractors","/jasonai/general-contractors"],["Interactive demo","/jasonai/demo"],["Trust","/jasonai/trust"]]},
"/jasonai/general-contractors":{eyebrow:"JasonAI / For general contractors",title:"Your executive secretary.",lead:"Stay on top of your crews, jobs, deliveries and payments without replacing your project manager.",sections:[["What needs your attention","A unified view of owner-level commitments.",[["Projects","Know which jobs changed and why."],["Labor","Capture who worked, where and what is owed."],["Deliveries","Surface arrival dates, changes and blockers."],["Approvals","Review updates with their source attached."]]]],links:[["Try the demo","/jasonai/demo"],["Trust","/jasonai/trust"]]},
"/jasonai/trust":{eyebrow:"JasonAI / Trust",title:"Your information. Your control.",lead:"Jason should know only what you choose to share and act within the permissions you assign.",sections:[["Operating principles","Control is designed into the workflow.",[["Selective access","Only connect the channels and information you authorize."],["Source visibility","Review where each proposed update came from."],["Human approval","Require owner approval for consequential messages or changes."]]]],links:[["See demo","/jasonai/demo"],["JasonAI","/jasonai"]]},
"/jasonai/demo":{eyebrow:"JasonAI / Interactive prototype",title:"From message to decision.",lead:"Explore a simplified message → memory → approval sequence. This is an illustrative prototype, not a connection to live communications.",demo:true,links:[["About JasonAI","/jasonai"],["How it works","/how-we-work"]]},
"/businesses":{eyebrow:"B2W / Businesses",title:"Systems for working teams.",lead:"Simple, connected operations for project-based businesses.",sections:[["Starting point","Make updates visible and actionable.",[["Capture","Bring important communications into one controlled view."],["Measure","Track work, labor and outstanding commitments."],["Improve","Identify the next useful automation."]]]],links:[["JasonAI","/jasonai"]]},
"/contact":{eyebrow:"B2W / Contact",title:"Start a conversation.",lead:"Describe one workflow that takes too much time or loses important information.",links:[["Our approach","/how-we-work"],["JasonAI","/jasonai"]]}
};
const app=document.querySelector("#app"),menu=document.querySelector("#site-menu"),btn=document.querySelector(".toggle");let step=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const demoFrames=[
["01 / Incoming message","“We finished framing on Oak Street. Marco and two workers stayed late.”","A selected project update enters the workflow."],
["02 / Business memory","Project: Oak Street · Labor: Marco + 2 · Update: framing finished","Jason links the message to labor and project context."],
["03 / Proposed action","Mark framing complete and request confirmation of crew hours?","The owner sees the proposed change and its source."],
["04 / Owner approval","Approved. Project context updated in this demonstration.","No external systems were changed."]
];
function renderDemo(){const root=document.querySelector("#demo-stage");if(!root)return;const [tag,message,detail]=demoFrames[step];root.innerHTML='<p class="eyebrow">'+tag+'</p><div class="demo-message">'+esc(message)+'</div><p>'+esc(detail)+'</p><div class="demo-actions"><button type="button" data-prev '+(step===0?'disabled':'')+'>Previous</button><button type="button" data-next>'+ (step===3?'Restart':'Continue') +'</button></div><p class="muted">Step '+(step+1)+' of 4 · Illustrative content</p>';}
function render(){const route=location.pathname.replace(/\/$/,"")||"/",p=pages[route];if(!p){app.innerHTML='<section class="hero"><h1>Page not found</h1><a data-route href="/">Home</a></section>';return;}document.title=p.title+" | B2W";app.innerHTML='<div class="hero"><p class="eyebrow">'+esc(p.eyebrow)+'</p><h1>'+esc(p.title)+'</h1><p class="lead">'+esc(p.lead)+'</p><div class="routes">'+p.links.map(([label,path])=>'<a data-route href="'+path+'">'+esc(label)+' <span>↗</span></a>').join("")+'</div></div>'+(p.sections||[]).map(([heading,sub,items])=>'<section class="content-section"><div class="section-intro"><p class="eyebrow">B2W / '+esc(heading)+'</p><h2>'+esc(heading)+'</h2><p>'+esc(sub)+'</p></div><div class="details">'+items.map(([t,d])=>'<article><h3>'+esc(t)+'</h3><p>'+esc(d)+'</p></article>').join("")+'</div></section>').join("")+(p.demo?'<section class="content-section"><div class="section-intro"><h2>See the flow</h2><p>Step through how one update becomes a reviewable decision.</p></div><div class="demo-panel" id="demo-stage"></div></section>':"");document.querySelectorAll('nav a').forEach(a=>a.toggleAttribute("aria-current",a.getAttribute("href")===route));if(p.demo){step=0;renderDemo();}}
document.addEventListener("click",e=>{if(e.target.closest("[data-next]")){step=(step+1)%4;renderDemo();return;}if(e.target.closest("[data-prev]")){step=Math.max(0,step-1);renderDemo();return;}const a=e.target.closest("a[data-route]");if(a&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&e.button===0){e.preventDefault();history.pushState({},"",a.getAttribute("href"));render();menu.classList.remove("open");btn.setAttribute("aria-expanded","false");scrollTo(0,0);}});
btn.addEventListener("click",()=>{const open=menu.classList.toggle("open");btn.setAttribute("aria-expanded",String(open));});addEventListener("popstate",render);render();